### ISSUE TITLE
Content-Length triggering `BadRequest` on DELETE method

### ISSUE THREAD

**Issue by luizfonseca** [door2door-io/fullstack-code-challenge#7]
On my testings ( and on Heroku as well ), `Content-Length` on DELETE method is giving `BadRequest` errors because the connection is expecting something and then hangs up, but removing this  from the api simulator makes everything works just fine.

I am not able to replicate on the Jest Specs as well.

This is the specific line on `api.js:41`

- `"Content-Length": Buffer.byteLength(data)`  - data is `null` on `DELETE`.

**Comment by nicolasiensen** [comment]
Hey @luizfonseca !

Maybe we should set `Content-Length` only if `data != null`?

You are welcome to submit a pull request to fix this issue ;)
